# Generated by Django 4.2.8 on 2024-01-03 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InputData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("create_date", models.DateTimeField()),
                ("sex", models.FloatField()),
                ("age", models.FloatField()),
                ("bwt", models.FloatField()),
                ("ht", models.FloatField()),
                ("PTINR_1", models.FloatField()),
                ("PTINR_2", models.FloatField()),
                ("PTINR_3", models.FloatField()),
                ("PTINR_4", models.FloatField()),
                ("WFR_1", models.FloatField()),
                ("WFR_2", models.FloatField()),
                ("WFR_3", models.FloatField()),
            ],
        ),
    ]
